# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a7524af7e44b6f84d5cc33d61b0b4f08fd8ac7eda763af86a2c44e639f77d13302355c6029a4c0dca82004931be9cf75568edecd8234afa387f16a75f99418e

test:
  secret_key_base: 2cdb0f46453cc701d94797e94938ae3cadb2884276a1ea535ebbfee23bfc909c6d4ed6eb7aeb3f5e9e98845ef2b4451cc4a1e03fce574637d70d89a30fe4e0de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
